# Generated by Django 5.2.3 on 2025-08-14 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='document_type',
            field=models.CharField(choices=[('DNI', 'DNI'), ('Pasaporte', 'Pasaporte'), ('Cedula', 'Cédula')], max_length=50),
        ),
    ]
