# Generated by Django 5.2.3 on 2025-08-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0002_alter_passenger_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='document_type',
            field=models.CharField(max_length=50),
        ),
    ]
