# Generated by Django 5.2.3 on 2025-08-14 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='airplanes/')),
                ('capacity', models.IntegerField()),
                ('rows', models.IntegerField()),
                ('columns', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Seating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('row', models.IntegerField()),
                ('column', models.IntegerField()),
                ('type', models.CharField(choices=[('Normal', 'Normal'), ('VIP', 'VIP')], default='Normal', max_length=100)),
                ('state', models.BooleanField(default=False)),
                ('airplane_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seatings', to='airplanes.airplane')),
            ],
        ),
    ]
