# Generated by Django 5.2.3 on 2025-08-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airplanes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airplane',
            name='columns',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='airplane',
            name='rows',
            field=models.IntegerField(null=True),
        ),
    ]
