# Generated by Django 5.2.3 on 2025-08-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airplanes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airplane',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='airplanes/'),
        ),
    ]
