# Generated by Django 5.2.3 on 2025-08-14 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airplanes', '0002_alter_airplane_columns_alter_airplane_rows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seating',
            name='airplane_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airplanes.airplane'),
        ),
        migrations.AlterField(
            model_name='seating',
            name='number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='seating',
            name='type',
            field=models.CharField(choices=[('Normal', 'Normal'), ('VIP', 'VIP')], default='Normal', max_length=10),
        ),
    ]
