# Generated by Django 5.2.3 on 2025-08-14 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('airplanes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='flights/')),
                ('departure_date', models.DateTimeField(auto_now_add=True)),
                ('arrival_date', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('status', models.CharField(choices=[('Programado', 'Programado'), ('En vuelo', 'En vuelo'), ('Aterrizado', 'Aterrizado'), ('Cancelado', 'Cancelado')], default='Programado', max_length=20)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('airplane_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='airplanes.airplane')),
            ],
        ),
    ]
