# Generated by Django 5.2.3 on 2025-08-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
        ('passengers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='account_flight',
            field=models.ManyToManyField(blank=True, to='passengers.passenger'),
        ),
    ]
