# Generated by Django 5.2.3 on 2025-08-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_alter_flight_account_flight'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='flights/'),
        ),
    ]
