# Generated by Django 5.2.3 on 2025-08-14 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_flight_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='state',
        ),
        migrations.AddField(
            model_name='flight',
            name='status',
            field=models.CharField(choices=[('Programado', 'Programado'), ('En vuelo', 'En vuelo'), ('Aterrizado', 'Aterrizado'), ('Cancelado', 'Cancelado')], default='Programado', max_length=20),
        ),
    ]
