# Generated by Django 5.2.3 on 2025-08-14 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_remove_flight_state_flight_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='account_flight',
        ),
    ]
