# Generated by Django 5.2.3 on 2025-08-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_remove_flight_account_flight'),
        ('passengers', '0003_alter_passenger_document_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='status',
        ),
        migrations.AddField(
            model_name='flight',
            name='account_flight',
            field=models.ManyToManyField(blank=True, to='passengers.passenger'),
        ),
        migrations.AddField(
            model_name='flight',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
